trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Readme.md
    - resoruces/*
    - .ado/*

pool:
  vmImage: ubuntu-latest

variables:
- group: feed-variable-group
- group: acr-variable-group

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: $(artifacts_feed_name)
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: Docker@2
  inputs:
    containerRegistry: $(acr_connection_name)
    repository: $(repository_name)
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: $(acr_connection_name)
    repository: $(repository_name)
    command: 'push'
